# Generated by Django 3.2 on 2022-06-15 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resttype',
            name='resttype',
            field=models.CharField(max_length=50),
        ),
    ]
