# Generated by Django 3.2 on 2022-06-15 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0002_alter_resttype_resttype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resttype',
        ),
    ]
