# Generated by Django 3.2 on 2021-06-16 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0010_choice_poll'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='vote_entry',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='poll', to='learning_logs.entry'),
            preserve_default=False,
        ),
    ]
