# Generated by Django 3.2 on 2021-06-16 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0011_poll_vote_entry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='vote_entry',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Poll',
        ),
    ]
