# Generated by Django 3.2 on 2021-06-16 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0013_auto_20210616_2116'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
