# Generated by Django 3.2 on 2021-06-16 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0014_delete_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
