# Generated by Django 3.2 on 2021-07-01 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0016_topic_topicimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='topicimage',
        ),
    ]
