# Generated by Django 3.2 on 2021-07-02 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0021_alter_topic_topicimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='topicimage',
            field=models.ImageField(blank=True, default='images/111.jpg', null=True, upload_to='images'),
        ),
    ]
