# Generated by Django 3.2 on 2021-07-03 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0022_alter_topic_topicimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='topicimage',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
