# Generated by Django 3.2 on 2021-07-03 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0024_auto_20210703_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
