# Generated by Django 3.2 on 2021-07-04 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0025_alter_entry_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='entryimage',
            field=models.ImageField(blank=True, default='images/defaultimage.png', null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='topicimage',
            field=models.ImageField(blank=True, default='images/defaultimage.png', null=True, upload_to='images'),
        ),
    ]
