# Generated by Django 3.2 on 2021-06-27 19:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogtopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogtext', models.CharField(max_length=200)),
                ('blogdate_added', models.DateTimeField(auto_now_add=True)),
                ('blogowner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Blogentry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogtitle', models.CharField(max_length=50)),
                ('blogtext', models.TextField()),
                ('blogdate_added', models.DateTimeField(auto_now_add=True)),
                ('bloglike', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('blogtopic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blogtopic')),
            ],
            options={
                'verbose_name_plural': 'entries',
            },
        ),
        migrations.CreateModel(
            name='Blogcomment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogbody', models.TextField()),
                ('blogcreated', models.DateTimeField(auto_now_add=True)),
                ('blogupdated', models.DateTimeField(auto_now=True)),
                ('blogactive', models.BooleanField(default=True)),
                ('blogname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('blogpost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogcomments', to='blog.blogentry')),
            ],
        ),
    ]
