# Generated by Django 3.2 on 2021-06-29 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_alter_blogentry_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogtopic',
            name='blogowner',
        ),
        migrations.AddField(
            model_name='blogentry',
            name='blogentryowner',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='blogentryowner', to='auth.user'),
            preserve_default=False,
        ),
    ]
