# Generated by Django 3.2 on 2021-07-03 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210629_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogentry',
            name='blogentryimage',
            field=models.ImageField(blank=True, default='images/entrydefault.jpg', null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='blogtopic',
            name='blogtopicimage',
            field=models.ImageField(blank=True, default='images/topicdefault.jpg', null=True, upload_to='images'),
        ),
    ]
