# Generated by Django 3.2 on 2021-07-03 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blogentry_blogtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogtopic',
            name='blogtopicimage',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
