# Generated by Django 3.2 on 2021-07-04 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_blogtopic_blogtopicimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogentry',
            name='blogentryimage',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='blogtopic',
            name='blogtopicimage',
            field=models.ImageField(blank=True, default='images/default.jpg', null=True, upload_to='images'),
        ),
    ]
