# Generated by Django 3.2 on 2021-07-04 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210704_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogentry',
            name='blogentryimage',
            field=models.ImageField(blank=True, default='images/default.jpg', null=True, upload_to='images'),
        ),
    ]
