# Generated by Django 3.2 on 2021-07-04 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20210704_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogentry',
            name='blogentryimage',
            field=models.ImageField(blank=True, default='images/defaultimage.png', null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='blogtopic',
            name='blogtopicimage',
            field=models.ImageField(blank=True, default='images/defaultimage.png', null=True, upload_to='images'),
        ),
    ]
